---
title: "Statistics Education Resources"
author: "Matthew Beckman"
date: ''
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Online Resources for Teaching Statistics

#### Website with materials related to today's session:  [https://mdbeckman.github.io/PSU-Grad-Orientation/](https://mdbeckman.github.io/PSU-Grad-Orientation/)

## General Resources 

#### Guidelines for Assessment and Instruction in Statistics Education (GAISE)
2016 GAISE College Report: [http://www.amstat.org/education/gaise](http://www.amstat.org/education/gaise)

*Recommended best practices for Statistics Education.  Short description of 6 recommendations accompanied by concrete implementation strategies, sample resources, references, etc.*

#### Consortium for the Advancement of Undergraduate Statistics Education (CAUSE)

<http://www.causeweb.org> 

*The resources tab provides lots of useful materials sorted by topic, such as applets, cartoons, powerpoint slides, tutorials, data, suggested interactive activities, and more.*

#### ASA’s Collection of Useful Links

<https://www.amstat.org/education/resourcesforundergradteachers.cfm>

*Useful links for undergraduate teachers of statistics.  Clicking on “Useful Web Sites for Teachers” will bring up many more useful links.*

#### Statistics Education Blogs

- Teaching with Simulation-Based Inference: <https://www.causeweb.org/sbi/>
- Teach Data Science: <https://teachdatascience.com/intro/>
- Ask Good Questions: <https://askgoodquestions.blog/>


## Data Repositories

#### Chance News Wiki:
<http://test.causeweb.org/wiki/chance/index.php/Main_Page>

*Reviews current stories in the news that involve probability or statistical concepts.*

#### Chance Magazine’s “Taking a Chance in the Classroom”

<http://chance.amstat.org/category/columns/taking-a-chance-in-the-classroom/>

*Datasets and corresponding papers with suggestions classroom use.  ASA login required.*


#### Journal of Statistics Education Data Archive

<http://www.amstat.org/publications/jse/jse_data_archive.htm> 

*More data, although not sorted by statistical topic so a bit harder to find appropriate data.*

#### Robin Lock’s Website: 

<http://it.stlawu.edu/~rlock/maa51/data.html>

*Links to other data sources*

#### Data and Story Library (DASL)  

<http://lib.stat.cmu.edu/DASL/>

*Lots of real data, searchable by real-world topic or statistical method.*

#### StatLib – Datasets Archive
<http://lib.stat.cmu.edu/datasets/>

*One of the original sources for archived data*

#### Lots more...

<https://data.cityofnewyork.us/>

<https://github.com/fivethirtyeight/data>

<http://www.datasciencecentral.com/profiles/blogs/great-github-list-of-public-data-sets>

<http://www.icpsr.umich.edu/icpsrweb/ICPSR/>

<https://www.springboard.com/blog/free-public-data-sets-data-science-project/>

<https://www.dataquest.io/blog/free-datasets-for-projects/>

[Even more... (link)](http://bfy.tw/DOFS)


## Applets
  
#### Lock^5^ StatKey

<http://www.lock5stat.com/statkey>

*Sampling distributions, bootstrapping, randomization tests, theoretical distribution “tables”*

#### onlinestatbook.com

<http://onlinestatbook.com/stat_sim/index.html>

*Lots of applets, all searchable by statistical topic.*

#### Rossman and Chance Applets

<http://www.rossmanchance.com/applets/>

*Website for applets, many of which coincide with interactive activities.*


